name: MapGallery
main: tech.underside.mapgallery.MapGalleryPlugin
version: 0.45.0
api-version: '1.21'
authors: [ "MikelPlayz" ]
commands:
  gallery:
    description: Open and manage map gallery
    usage: /gallery [give|search|reload|remove]
permissions:
  mapgallery.gallery:
    description: Open gallery GUI
    default: true
  mapgallery.give:
    description: Give a map by gallery id
    default: op
  mapgallery.admin:
    description: Remove gallery entries
    default: op
  mapgallery.reload:
    description: Reload plugin configuration
    default: op
